export const titleStates = {
	acuteRhinitis: 'Острый ринит?',
	acuteTonsillitis: 'Острый тонзиллит?',
	acutePharyngitis: 'Острый фарингит?',
	acuteTracheitis: 'Острый трахеит?',
	acuteBronchitis: 'Острый бронхит?',
	acuteObstructiveBronchitis: 'Острый обструктивный бронхит?',
	acuteBronchiolitis: 'Острый бронхиолит?',
	pleuritis: 'Плеврит?',
	bronchoectaticLungCondition: 'Бронхоэктатическая болезнь легких?',
	chronicRhinitis: 'Хронический ринит?',
	chronicTonsillitis: 'Хронический тонзиллит?',
	chronicPharyngitis: 'Хронический фарингит?',
	cough: 'Кашель, неясной этиологии?',
	chronicBronchitis: 'Хронический бронхит?',
	copd: 'ХОБЛ?',
	bronchialAsthma: 'Бронхиальная астма?',
	pneumonia: 'Внегоспитальная пневмония?',
	pneumoniaWithBloodThroating: 'Внегоспитальная пневмония, осложненная кровохарканьем?',
	pulmonaryTuberculosis: 'Туберкулез легких?',
	tela: 'ТЭЛА?',
	pulmonaryInfarction: 'Инфаркт-пневмония легких?',
	pollinosis: 'Поллиноз?',
	respiratoryProtection: 'Защита органов дыхания при помощи респиратора.',
	rejectionBadHabits: 'Отказ от вредных привычек.',
	noPathology: 'На данный момент патологии не выявлено.',
};
